#!/bin/bash
# Generates frontend/config.js from environment variables
# Usage: TURNSTILE_SITE_KEY=xxx ./scripts/build-config.sh

set -e

if [ -z "$TURNSTILE_SITE_KEY" ]; then
    echo "Error: TURNSTILE_SITE_KEY environment variable is required"
    exit 1
fi

cat > frontend/config.js << EOF
// Auto-generated by build-config.sh - DO NOT EDIT
window.MLEM_CONFIG = {
    TURNSTILE_SITE_KEY: '${TURNSTILE_SITE_KEY}',
};
EOF

echo "Generated frontend/config.js"
